In [1]:
import pandas as pd
import os

In [3]:
tips=pd.read_csv('tips.csv')

In [4]:
tips

     total_bill   tip     sex smoker   day    time  size
0         16.99  1.01  Female     No   Sun  Dinner     2
1         10.34  1.66    Male     No   Sun  Dinner     3
2         21.01  3.50    Male     No   Sun  Dinner     3
3         23.68  3.31    Male     No   Sun  Dinner     2
4         24.59  3.61  Female     No   Sun  Dinner     4
5         25.29  4.71    Male     No   Sun  Dinner     4
6          8.77  2.00    Male     No   Sun  Dinner     2
7         26.88  3.12    Male     No   Sun  Dinner     4
8         15.04  1.96    Male     No   Sun  Dinner     2
9         14.78  3.23    Male     No   Sun  Dinner     2
10        10.27  1.71    Male     No   Sun  Dinner     2
11        35.26  5.00  Female     No   Sun  Dinner     4
12        15.42  1.57    Male     No   Sun  Dinner     2
13        18.43  3.00    Male     No   Sun  Dinner     4
14        14.83  3.02  Female     No   Sun  Dinner     2
15        21.58  3.92    Male     No   Sun  Dinner     2
16        10.33  1.67  Female     No   Sun  Dinner     3
17        16.29  3.71    Male     No   Sun  Dinner     3
18        16.97  3.50  Female     No   Sun  Dinner     3
19        20.65  3.35    Male     No   Sat  Dinner     3
20        17.92  4.08    Male     No   Sat  Dinner     2
21        20.29  2.75  Female     No   Sat  Dinner     2
22        15.77  2.23  Female     No   Sat  Dinner     2
23        39.42  7.58    Male     No   Sat  Dinner     4
24        19.82  3.18    Male     No   Sat  Dinner     2
25        17.81  2.34    Male     No   Sat  Dinner     4
26        13.37  2.00    Male     No   Sat  Dinner     2
27        12.69  2.00    Male     No   Sat  Dinner     2
28        21.70  4.30    Male     No   Sat  Dinner     2
29        19.65  3.00  Female     No   Sat  Dinner     2
..          ...   ...     ...    ...   ...     ...   ...
214       28.17  6.50  Female    Yes   Sat  Dinner     3
215       12.90  1.10  Female    Yes   Sat  Dinner     2
216       28.15  3.00    Male    Yes   Sat  Dinner     5
217       11.59  1.50    Male    Yes   Sat  Dinner     2
218        7.74  1.44    Male    Yes   Sat  Dinner     2
219       30.14  3.09  Female    Yes   Sat  Dinner     4
220       12.16  2.20    Male    Yes   Fri   Lunch     2
221       13.42  3.48  Female    Yes   Fri   Lunch     2
222        8.58  1.92    Male    Yes   Fri   Lunch     1
223       15.98  3.00  Female     No   Fri   Lunch     3
224       13.42  1.58    Male    Yes   Fri   Lunch     2
225       16.27  2.50  Female    Yes   Fri   Lunch     2
226       10.09  2.00  Female    Yes   Fri   Lunch     2
227       20.45  3.00    Male     No   Sat  Dinner     4
228       13.28  2.72    Male     No   Sat  Dinner     2
229       22.12  2.88  Female    Yes   Sat  Dinner     2
230       24.01  2.00    Male    Yes   Sat  Dinner     4
231       15.69  3.00    Male    Yes   Sat  Dinner     3
232       11.61  3.39    Male     No   Sat  Dinner     2
233       10.77  1.47    Male     No   Sat  Dinner     2
234       15.53  3.00    Male    Yes   Sat  Dinner     2
235       10.07  1.25    Male     No   Sat  Dinner     2
236       12.60  1.00    Male    Yes   Sat  Dinner     2
237       32.83  1.17    Male    Yes   Sat  Dinner     2
238       35.83  4.67  Female     No   Sat  Dinner     3
239       29.03  5.92    Male     No   Sat  Dinner     3
240       27.18  2.00  Female    Yes   Sat  Dinner     2
241       22.67  2.00    Male    Yes   Sat  Dinner     2
242       17.82  1.75    Male     No   Sat  Dinner     2
243       18.78  3.00  Female     No  Thur  Dinner     2

[244 rows x 7 columns]

In [5]:
tips['mycal']=tips.total_bill*tips.tip

In [6]:
tips

     total_bill   tip     sex smoker   day    time  size     mycal
0         16.99  1.01  Female     No   Sun  Dinner     2   17.1599
1         10.34  1.66    Male     No   Sun  Dinner     3   17.1644
2         21.01  3.50    Male     No   Sun  Dinner     3   73.5350
3         23.68  3.31    Male     No   Sun  Dinner     2   78.3808
4         24.59  3.61  Female     No   Sun  Dinner     4   88.7699
5         25.29  4.71    Male     No   Sun  Dinner     4  119.1159
6          8.77  2.00    Male     No   Sun  Dinner     2   17.5400
7         26.88  3.12    Male     No   Sun  Dinner     4   83.8656
8         15.04  1.96    Male     No   Sun  Dinner     2   29.4784
9         14.78  3.23    Male     No   Sun  Dinner     2   47.7394
10        10.27  1.71    Male     No   Sun  Dinner     2   17.5617
11        35.26  5.00  Female     No   Sun  Dinner     4  176.3000
12        15.42  1.57    Male     No   Sun  Dinner     2   24.2094
13        18.43  3.00    Male     No   Sun  Dinner     4   55.2900
14        14.83  3.02  Female     No   Sun  Dinner     2   44.7866
15        21.58  3.92    Male     No   Sun  Dinner     2   84.5936
16        10.33  1.67  Female     No   Sun  Dinner     3   17.2511
17        16.29  3.71    Male     No   Sun  Dinner     3   60.4359
18        16.97  3.50  Female     No   Sun  Dinner     3   59.3950
19        20.65  3.35    Male     No   Sat  Dinner     3   69.1775
20        17.92  4.08    Male     No   Sat  Dinner     2   73.1136
21        20.29  2.75  Female     No   Sat  Dinner     2   55.7975
22        15.77  2.23  Female     No   Sat  Dinner     2   35.1671
23        39.42  7.58    Male     No   Sat  Dinner     4  298.8036
24        19.82  3.18    Male     No   Sat  Dinner     2   63.0276
25        17.81  2.34    Male     No   Sat  Dinner     4   41.6754
26        13.37  2.00    Male     No   Sat  Dinner     2   26.7400
27        12.69  2.00    Male     No   Sat  Dinner     2   25.3800
28        21.70  4.30    Male     No   Sat  Dinner     2   93.3100
29        19.65  3.00  Female     No   Sat  Dinner     2   58.9500
..          ...   ...     ...    ...   ...     ...   ...       ...
214       28.17  6.50  Female    Yes   Sat  Dinner     3  183.1050
215       12.90  1.10  Female    Yes   Sat  Dinner     2   14.1900
216       28.15  3.00    Male    Yes   Sat  Dinner     5   84.4500
217       11.59  1.50    Male    Yes   Sat  Dinner     2   17.3850
218        7.74  1.44    Male    Yes   Sat  Dinner     2   11.1456
219       30.14  3.09  Female    Yes   Sat  Dinner     4   93.1326
220       12.16  2.20    Male    Yes   Fri   Lunch     2   26.7520
221       13.42  3.48  Female    Yes   Fri   Lunch     2   46.7016
222        8.58  1.92    Male    Yes   Fri   Lunch     1   16.4736
223       15.98  3.00  Female     No   Fri   Lunch     3   47.9400
224       13.42  1.58    Male    Yes   Fri   Lunch     2   21.2036
225       16.27  2.50  Female    Yes   Fri   Lunch     2   40.6750
226       10.09  2.00  Female    Yes   Fri   Lunch     2   20.1800
227       20.45  3.00    Male     No   Sat  Dinner     4   61.3500
228       13.28  2.72    Male     No   Sat  Dinner     2   36.1216
229       22.12  2.88  Female    Yes   Sat  Dinner     2   63.7056
230       24.01  2.00    Male    Yes   Sat  Dinner     4   48.0200
231       15.69  3.00    Male    Yes   Sat  Dinner     3   47.0700
232       11.61  3.39    Male     No   Sat  Dinner     2   39.3579
233       10.77  1.47    Male     No   Sat  Dinner     2   15.8319
234       15.53  3.00    Male    Yes   Sat  Dinner     2   46.5900
235       10.07  1.25    Male     No   Sat  Dinner     2   12.5875
236       12.60  1.00    Male    Yes   Sat  Dinner     2   12.6000
237       32.83  1.17    Male    Yes   Sat  Dinner     2   38.4111
238       35.83  4.67  Female     No   Sat  Dinner     3  167.3261
239       29.03  5.92    Male     No   Sat  Dinner     3  171.8576
240       27.18  2.00  Female    Yes   Sat  Dinner     2   54.3600
241       22.67  2.00    Male    Yes   Sat  Dinner     2   45.3400
242       17.82  1.75    Male     No   Sat  Dinner     2   31.1850
243       18.78  3.00  Female     No  Thur  Dinner     2   56.3400

[244 rows x 8 columns]

In [7]:
tips.to_csv('updated_csv_tips.csv')